### ISSUE TITLE
Setup tasks

### ISSUE THREAD

**Issue by dacb** [Cargill-Capstone2021/ADME-modeling-for-Cargill#1]
Let's get the directory setup going with some pieces for CI, e.g. `.travis.yml` and the project scaffold.

I saw the use cases were approved.  Can we put together a Gantt and a timeline?  Also, are any of the existing papers in this space have published models on GitHub?

**Comment by burrows181** [comment]
I found a published paper by Delaney - predicting the solubility of molecules using a regression model. They used RDKIT package to convert the SMILES string to rdkit object (which we can maybe try to use the same). Their model was reproduced and I uploaded the notebook for it on our GitHub.
